## Câu 1 – Naïve Bayes với Iris (GaussianNB – demo cơ bản)

In [5]:
# naive_bayes_iris.py
# Demo Naïve Bayes phân loại loài hoa Iris

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def main():
    # 1. Load dữ liệu Iris
    iris = load_iris()
    X = iris.data           # 4 thuộc tính: sepal length, sepal width, petal length, petal width
    y = iris.target         # 3 lớp: 0=setosa, 1=versicolor, 2=virginica
    target_names = iris.target_names

    # 2. Chia train/test
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42, stratify=y
    )

    # 3. Khởi tạo mô hình Naïve Bayes (Gaussian)
    model = GaussianNB()

    # 4. Huấn luyện
    model.fit(X_train, y_train)

    # 5. Dự đoán trên tập test
    y_pred = model.predict(X_test)

    # 6. Đánh giá
    acc = accuracy_score(y_test, y_pred)
    print("=== Kết quả Naïve Bayes trên Iris ===")
    print(f"Độ chính xác (Accuracy): {acc:.4f}\n")

    print("=== Classification Report ===")
    print(classification_report(y_test, y_pred, target_names=target_names))

    print("=== Confusion Matrix ===")
    print(confusion_matrix(y_test, y_pred))

    # 7. Demo dự đoán thử 1 mẫu
    sample = [[5.1, 3.5, 1.4, 0.2]]  # một mẫu giống setosa
    sample_pred = model.predict(sample)[0]
    print("\nDự đoán cho mẫu", sample, "=> lớp:", target_names[sample_pred])

if __name__ == "__main__":
    main()


=== Kết quả Naïve Bayes trên Iris ===
Độ chính xác (Accuracy): 0.9111

=== Classification Report ===
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       0.82      0.93      0.87        15
   virginica       0.92      0.80      0.86        15

    accuracy                           0.91        45
   macro avg       0.92      0.91      0.91        45
weighted avg       0.92      0.91      0.91        45

=== Confusion Matrix ===
[[15  0  0]
 [ 0 14  1]
 [ 0  3 12]]

Dự đoán cho mẫu [[5.1, 3.5, 1.4, 0.2]] => lớp: setosa


## Câu 2 – Naïve Bayes nhận dạng ký tự (UCI Letter Recognition)

In [6]:
# naive_bayes_letter_recognition.py
# Nhận dạng ký tự A-Z dùng Naïve Bayes với UCI Letter Recognition

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def main():
    # 1. Đọc dữ liệu từ file (20,000 mẫu, 1 cột label + 16 cột đặc trưng)
    # Tải từ https://archive.ics.uci.edu/ml/datasets/letter+recognition
    # và lưu thành 'letter-recognition.data'
    file_path = "letter-recognition.data"

    # Không có header trong file, tự đặt tên cột
    col_names = ["letter"] + [f"x{i}" for i in range(1, 17)]
    df = pd.read_csv(file_path, header=None, names=col_names)

    # 2. Tách X, y
    X = df.iloc[:, 1:].values  # 16-D feature
    y = df["letter"].values    # nhãn A-Z

    # 3. Mã hóa nhãn chữ cái thành số (A->0, B->1, ..., Z->25)
    label_encoder = LabelEncoder()
    y_encoded = label_encoder.fit_transform(y)

    # 4. Chia train/test
    X_train, X_test, y_train, y_test = train_test_split(
        X, y_encoded, test_size=0.3, random_state=42, stratify=y_encoded
    )

    # 5. Khởi tạo mô hình Naïve Bayes
    model = GaussianNB()

    # 6. Huấn luyện
    model.fit(X_train, y_train)

    # 7. Dự đoán trên tập test
    y_pred = model.predict(X_test)

    # 8. Đánh giá
    acc = accuracy_score(y_test, y_pred)
    print("=== Kết quả Naïve Bayes trên Letter Recognition ===")
    print(f"Độ chính xác (Accuracy): {acc:.4f}\n")

    print("=== Classification Report (A-Z) ===")
    # Chuyển lại từ số -> chữ A-Z cho dễ đọc
    target_names = label_encoder.inverse_transform(sorted(set(y_encoded)))
    print(classification_report(y_test, y_pred, target_names=target_names))

    print("=== Confusion Matrix ===")
    print(confusion_matrix(y_test, y_pred))

    # 9. Demo dự đoán 1 mẫu bất kỳ
    sample = X_test[0].reshape(1, -1)
    sample_true = label_encoder.inverse_transform([y_test[0]])[0]
    sample_pred = label_encoder.inverse_transform(model.predict(sample))[0]
    print("\nMẫu test đầu tiên:")
    print("  Nhãn thật:", sample_true)
    print("  Mô hình dự đoán:", sample_pred)

if __name__ == "__main__":
    main()


=== Kết quả Naïve Bayes trên Letter Recognition ===
Độ chính xác (Accuracy): 0.6448

=== Classification Report (A-Z) ===
              precision    recall  f1-score   support

           A       0.83      0.84      0.84       237
           B       0.47      0.72      0.57       230
           C       0.79      0.80      0.80       221
           D       0.58      0.73      0.65       242
           E       0.58      0.36      0.44       230
           F       0.69      0.77      0.73       232
           G       0.58      0.54      0.56       232
           H       0.55      0.33      0.41       220
           I       0.53      0.72      0.61       226
           J       0.84      0.72      0.78       224
           K       0.46      0.49      0.47       222
           L       0.92      0.77      0.84       228
           M       0.69      0.88      0.78       238
           N       0.87      0.68      0.77       235
           O       0.48      0.73      0.58       226
           P  